Connect product database
pass-culture/data-science pull request #37
Opened 2020-10-13 10:00 UTC by jrovani

2020-10-13 13:41 UTC, bourliam reviewed
Remarques générales :
- Je suis pas fan de mettre des images dans un github : quand on fait la PR on voir pas l'image... et les images etc sont plutôt dans le notion
- C'est pas forcément évident vu que tu viens d'arriver sur le projet mais faut essayer de garder la même logique de code entre les fichiers, donc hésite pas à regarder ce qui a déjà été fait pour être cohérent, quitte a faire des améliorations sur l'existant.

2020-10-13 13:41 UTC, bourliam commented on .env.dist
> +PRODUCT_DATABASE_CONNECTION=<>
si les variables sont dans l'env du jupyterhub, on a pas besoin du env.dist non ?
Et sinon il a l'air de manquer le export sur les deux dernières lignes

2020-10-13 13:41 UTC, bourliam commented on requirements.txt
> +sshtunnel==0.1.5
Pour le moment on a privilégié la création du tunnel ssh via les commandes bash lancées avec subprocess. => ce serait mieux de continuer à faire pareil, ou alors uniformiser

2020-10-13 13:41 UTC, bourliam commented on scripts/query_product_database.py
> +"""
On a comme standard de mettre le moins de docstring possible et d'avoir un code auto-porteur, donc pas besoin ici

2020-10-13 13:41 UTC, bourliam commented on scripts/query_product_database.py
> +    private_key_path="/home/jean/.ssh/id_rsa", **SSH
c'est du code qui marche que sur ta machine ça....

2020-10-13 13:41 UTC, bourliam commented on scripts/query_product_database.py
> +dataframe = product_database_connection.query_database(query=f'SELECT * FROM "stock" limit 10;', **CONNECTION)
code résiduel ?

2020-10-13 13:41 UTC, bourliam commented on scripts/query_product_database.py
> +print(dataframe)
pareil, pourquoi tu print les stocks ?

2020-10-13 13:41 UTC, bourliam commented on src/data_access/product_database_connection.py
> +        self.ssh_remote_bind_port = ssh_remote_bind_port
pour les noms d'arguments est-ce que tu peux t'aligner sur ceux qu'on a utilisé ailleurs pour les connexion ssh ? ça doit être dans le code push par ferdi, ou alors dans data-maintenance.

2020-10-13 13:41 UTC, bourliam commented on src/data_access/query_initial_responses.py
> +            before (string): limit request to responses submitted before a request token.
Il me semble que Romain avait mis comme commentaires d'enlever les args de la docstring. C'est hors-standards en tout cas.

2020-10-13 14:21 UTC, jrovani commented on .env.dist
> +PRODUCT_DATABASE_CONNECTION=<>
effectivement, il manque les export.

Je trouve que c'est une bonne pratique de préciser les variables d'environnement nécessaires dans le repo, notamment car on peut vouloir à l'avenir se servir du code autre part que sur jupyter

2020-10-13 14:25 UTC, jrovani commented on scripts/query_product_database.py
> +    private_key_path="/home/jean/.ssh/id_rsa", **SSH
oui, c'est un exemple pour pouvoir être facilement utilisé dans un notebook

2020-10-13 15:27 UTC, jrovani commented on src/data_access/query_initial_responses.py
> +            before (string): limit request to responses submitted before a request token.
on est tombés d'accord pour la conserver finalement

2020-10-15 15:21 UTC, bourliam approved these changes

2020-10-15 16:29 UTC, FerdiHr requested changes

2020-10-15 16:29 UTC, FerdiHr commented on src/data_access/database_connection.py
> +
Il faut fixer la question de la première connexion avec l'acceptation de l'identité du serveur... Peut-être une commande stockée dans le 1password ? => mettre le tuto dans le README

2020-10-16 08:59 UTC, FerdiHr approved these changes

2020-10-16 09:01 UTC, merged